version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: community-platform-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: community-platform-db
    ports:
      - "5444:5432"
